spring.datasource.url=jdbc:mysql://garistyle.synology.me:3306/test
spring.datasource.username=gari
spring.datasource.password=Kwan@0504!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.megacoffee
mybatis.configuration.map-underscore-to-camel-case=true

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/resources
spring.devtools.livereload.enabled=true

server.port=8081
server.servlet.session.timeout=5h
